# Generated by Django 6.0.6 on 2026-06-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_seat_show_seat_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=8),
        ),
    ]
