# Generated by Django 6.0.6 on 2026-06-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_review_one_review_per_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
    ]
